version: "3.8"
services: 
  mongo:
    container_name: mongo
    build:
      context: "db/mongo"
      dockerfile: Dockerfile
    image: index.docker.io/caliguy2322/waitmemongo:2
    ports:
      - '27017:27017'
    networks:
      - app-bridge  
  api:
    container_name: api
    build:
      context: "api"
      dockerfile: Dockerfile
    image: index.docker.io/caliguy2322/waitmeapi:2
    ports:
      - "5000:5000"
    networks: 
      - app-bridge    
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile   
    image: index.docker.io/caliguy2322/waitmefrontend:2
    networks: 
      - app-bridge  
    ports:
      - "3000:3000"
    stdin_open: true
networks:
  app-bridge:
    driver: bridge        
           