export const FETCH_PARTIES = "FETCH_PARTIES"
export const FETCH_TABLES = "FETCH_TABLES"
export const FETCH_TABLES_STATUS = "FETCH_TABLES_STATUS"
export const UPDATE_PARTY_STATE = "UPDATE_PARTY_STATE"
export const UPDATE_TABLE_STATUS = "UPDATE_TABLE_STATUS"
export const CREATE_WAITLIST = "CREATE_WAITLIST"
export const UPDATE_WAITLIST = "UPDATE_WAITLIST"
export const UPDATE_WAITLIST_MSG = "UPDATE_WAITLIST_MSG"
export const UPDATE_RESERVATION_MSG = "UPDATE_RESERVATION_MSG"
export const CREATE_RESERVATION = "CREATE_RESERVATION"
export const UPDATE_RESERVATION = "UPDATE_RESERVATION"
export const CREATE_WALKIN = "CREATE_WALKIN"


